modLoader = "kotlinforforge"
loaderVersion = "[4.6,)"
license = "MIT"
issueTrackerURL = "https://github.com/skyecodes/IBE-Editor-New/issues"

[[mods]]
modId = "ibeeditor"
version = "${version}"
displayName = "IBE Editor"
#updateJSONURL="http://myurl.me/"
displayURL = "https://modrinth.com/mod/ibe-editor"
logoFile = "banner.png"
#credits=""
authors = "skyecodes"
displayTest = "IGNORE_ALL_VERSION"
description = '''
Simple GUI Mod to edit an item, a block or an entity in your current world
'''

[[dependencies.ibeeditor]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ibeeditor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.21)"
ordering = "NONE"
side = "BOTH"
